version: '3'
services:
  arrebato-0:
    build:
      context: .
    stop_grace_period: "60s"
    restart: on-failure
    command:
      - server
      - --log-level=2
      - --advertise-address=arrebato-0
    ports:
      - "5000:5000"
    networks:
      - default

  arrebato-1:
    build:
      context: .
    stop_grace_period: "60s"
    restart: on-failure
    command:
      - server
      - --peers=arrebato-0
      - --log-level=2
      - --advertise-address=arrebato-1
    ports:
      - "5001:5000"
    depends_on:
      - arrebato-0
    networks:
      - default

  arrebato-2:
    build:
      context: .
    stop_grace_period: "60s"
    restart: on-failure
    command:
      - server
      - --peers=arrebato-0
      - --log-level=2
      - --advertise-address=arrebato-2
    ports:
      - "5002:5000"
    depends_on:
      - arrebato-1
    networks:
      - default

networks:
  default: {}
