kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
namespace: arrebato

images:
  - name: ghcr.io/davidsbond/arrebato
    newTag: v0.1.0-alpha1

resources:
  - namespace.yaml
  - statefulset.yaml
  - service.yaml
