kind: Service
apiVersion: v1
metadata:
  name: arrebato
spec:
  clusterIP: None
  selector:
    app: arrebato
  ports:
    - port: 5000
      targetPort: grpc
      protocol: TCP
      name: grpc
    - port: 5001
      targetPort: serf
      protocol: TCP
      name: serf
