// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        (unknown)
// source: arrebato/acl/command/v1/command.proto

// Package arrebato.acl.command.v1 provides commands written to the raft log regarding acl state.
// These messages are used internally by nodes in the cluster to portray changes from the leader node to all followers.

package aclcmd

import (
	v1 "github.com/davidsbond/arrebato/internal/proto/arrebato/acl/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// The SetACL message is a command indicating that the server's ACL has changed.
type SetACL struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The new ACL state.
	Acl *v1.ACL `protobuf:"bytes,1,opt,name=acl,proto3" json:"acl,omitempty"`
}

func (x *SetACL) Reset() {
	*x = SetACL{}
	if protoimpl.UnsafeEnabled {
		mi := &file_arrebato_acl_command_v1_command_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetACL) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetACL) ProtoMessage() {}

func (x *SetACL) ProtoReflect() protoreflect.Message {
	mi := &file_arrebato_acl_command_v1_command_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetACL.ProtoReflect.Descriptor instead.
func (*SetACL) Descriptor() ([]byte, []int) {
	return file_arrebato_acl_command_v1_command_proto_rawDescGZIP(), []int{0}
}

func (x *SetACL) GetAcl() *v1.ACL {
	if x != nil {
		return x.Acl
	}
	return nil
}

var File_arrebato_acl_command_v1_command_proto protoreflect.FileDescriptor

var file_arrebato_acl_command_v1_command_proto_rawDesc = []byte{
	0x0a, 0x25, 0x61, 0x72, 0x72, 0x65, 0x62, 0x61, 0x74, 0x6f, 0x2f, 0x61, 0x63, 0x6c, 0x2f, 0x63,
	0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x2f, 0x76, 0x31, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e,
	0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x17, 0x61, 0x72, 0x72, 0x65, 0x62, 0x61, 0x74,
	0x6f, 0x2e, 0x61, 0x63, 0x6c, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x2e, 0x76, 0x31,
	0x1a, 0x19, 0x61, 0x72, 0x72, 0x65, 0x62, 0x61, 0x74, 0x6f, 0x2f, 0x61, 0x63, 0x6c, 0x2f, 0x76,
	0x31, 0x2f, 0x61, 0x63, 0x6c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x30, 0x0a, 0x06, 0x53,
	0x65, 0x74, 0x41, 0x43, 0x4c, 0x12, 0x26, 0x0a, 0x03, 0x61, 0x63, 0x6c, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x14, 0x2e, 0x61, 0x72, 0x72, 0x65, 0x62, 0x61, 0x74, 0x6f, 0x2e, 0x61, 0x63,
	0x6c, 0x2e, 0x76, 0x31, 0x2e, 0x41, 0x43, 0x4c, 0x52, 0x03, 0x61, 0x63, 0x6c, 0x42, 0x4e, 0x5a,
	0x4c, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x64, 0x61, 0x76, 0x69,
	0x64, 0x73, 0x62, 0x6f, 0x6e, 0x64, 0x2f, 0x61, 0x72, 0x72, 0x65, 0x62, 0x61, 0x74, 0x6f, 0x2f,
	0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x61,
	0x72, 0x72, 0x65, 0x62, 0x61, 0x74, 0x6f, 0x2f, 0x61, 0x63, 0x6c, 0x2f, 0x63, 0x6f, 0x6d, 0x6d,
	0x61, 0x6e, 0x64, 0x2f, 0x76, 0x31, 0x3b, 0x61, 0x63, 0x6c, 0x63, 0x6d, 0x64, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_arrebato_acl_command_v1_command_proto_rawDescOnce sync.Once
	file_arrebato_acl_command_v1_command_proto_rawDescData = file_arrebato_acl_command_v1_command_proto_rawDesc
)

func file_arrebato_acl_command_v1_command_proto_rawDescGZIP() []byte {
	file_arrebato_acl_command_v1_command_proto_rawDescOnce.Do(func() {
		file_arrebato_acl_command_v1_command_proto_rawDescData = protoimpl.X.CompressGZIP(file_arrebato_acl_command_v1_command_proto_rawDescData)
	})
	return file_arrebato_acl_command_v1_command_proto_rawDescData
}

var file_arrebato_acl_command_v1_command_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_arrebato_acl_command_v1_command_proto_goTypes = []interface{}{
	(*SetACL)(nil), // 0: arrebato.acl.command.v1.SetACL
	(*v1.ACL)(nil), // 1: arrebato.acl.v1.ACL
}
var file_arrebato_acl_command_v1_command_proto_depIdxs = []int32{
	1, // 0: arrebato.acl.command.v1.SetACL.acl:type_name -> arrebato.acl.v1.ACL
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_arrebato_acl_command_v1_command_proto_init() }
func file_arrebato_acl_command_v1_command_proto_init() {
	if File_arrebato_acl_command_v1_command_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_arrebato_acl_command_v1_command_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetACL); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_arrebato_acl_command_v1_command_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_arrebato_acl_command_v1_command_proto_goTypes,
		DependencyIndexes: file_arrebato_acl_command_v1_command_proto_depIdxs,
		MessageInfos:      file_arrebato_acl_command_v1_command_proto_msgTypes,
	}.Build()
	File_arrebato_acl_command_v1_command_proto = out.File
	file_arrebato_acl_command_v1_command_proto_rawDesc = nil
	file_arrebato_acl_command_v1_command_proto_goTypes = nil
	file_arrebato_acl_command_v1_command_proto_depIdxs = nil
}
