// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             (unknown)
// source: arrebato/consumer/service/v1/service.proto

package consumersvc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ConsumerServiceClient is the client API for ConsumerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ConsumerServiceClient interface {
	// SetTopicIndex sets the current index of a consumer on a topic. This RPC should return a NOT_FOUND error code if the
	// topic does not exist.
	SetTopicIndex(ctx context.Context, in *SetTopicIndexRequest, opts ...grpc.CallOption) (*SetTopicIndexResponse, error)
}

type consumerServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewConsumerServiceClient(cc grpc.ClientConnInterface) ConsumerServiceClient {
	return &consumerServiceClient{cc}
}

func (c *consumerServiceClient) SetTopicIndex(ctx context.Context, in *SetTopicIndexRequest, opts ...grpc.CallOption) (*SetTopicIndexResponse, error) {
	out := new(SetTopicIndexResponse)
	err := c.cc.Invoke(ctx, "/arrebato.consumer.service.v1.ConsumerService/SetTopicIndex", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ConsumerServiceServer is the server API for ConsumerService service.
// All implementations should embed UnimplementedConsumerServiceServer
// for forward compatibility
type ConsumerServiceServer interface {
	// SetTopicIndex sets the current index of a consumer on a topic. This RPC should return a NOT_FOUND error code if the
	// topic does not exist.
	SetTopicIndex(context.Context, *SetTopicIndexRequest) (*SetTopicIndexResponse, error)
}

// UnimplementedConsumerServiceServer should be embedded to have forward compatible implementations.
type UnimplementedConsumerServiceServer struct {
}

func (UnimplementedConsumerServiceServer) SetTopicIndex(context.Context, *SetTopicIndexRequest) (*SetTopicIndexResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetTopicIndex not implemented")
}

// UnsafeConsumerServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ConsumerServiceServer will
// result in compilation errors.
type UnsafeConsumerServiceServer interface {
	mustEmbedUnimplementedConsumerServiceServer()
}

func RegisterConsumerServiceServer(s grpc.ServiceRegistrar, srv ConsumerServiceServer) {
	s.RegisterService(&ConsumerService_ServiceDesc, srv)
}

func _ConsumerService_SetTopicIndex_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetTopicIndexRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConsumerServiceServer).SetTopicIndex(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/arrebato.consumer.service.v1.ConsumerService/SetTopicIndex",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConsumerServiceServer).SetTopicIndex(ctx, req.(*SetTopicIndexRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ConsumerService_ServiceDesc is the grpc.ServiceDesc for ConsumerService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ConsumerService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "arrebato.consumer.service.v1.ConsumerService",
	HandlerType: (*ConsumerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SetTopicIndex",
			Handler:    _ConsumerService_SetTopicIndex_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "arrebato/consumer/service/v1/service.proto",
}
