name: distroless
on:
  workflow_dispatch: {}
  schedule:
    - cron: '0 12 * * *'

jobs:
  update:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Update base image
        run: make update-distroless
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          title: Update Distroless base image
          branch: update-distroless
          committer: GitHub <noreply@github.com>
          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          delete-branch: true
          base: master
          commit-message: |
            This commit updates the gcr.io/distroless/static digest to the latest known version
          body: |
            This commit updates the gcr.io/distroless/static digest to the latest known version
          labels: dependencies,docker
